# Generated by Django 5.2.7 on 2025-10-18 12:30

import app.domain.models.base_model
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=128, unique=True)),
                ("menu_type", models.SmallIntegerField()),
                ("rank", models.IntegerField()),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                ("component", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField()),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("meta_id", models.CharField(max_length=32)),
                ("parent_id", models.CharField(blank=True, max_length=32, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("redirect", models.CharField(blank=True, max_length=255, null=True)),
                ("hidden", models.BooleanField()),
                ("cache", models.BooleanField()),
                ("sort", models.IntegerField()),
                ("status", models.BooleanField()),
                ("remark", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_menu",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuMeta",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("title", models.CharField(max_length=128)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("hidden", models.BooleanField()),
                ("cache", models.BooleanField()),
                ("sort", models.IntegerField()),
                ("status", models.BooleanField()),
                ("remark", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_menu_meta",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("code", models.CharField(default="", max_length=128, unique=True)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "db_table": "system_role",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.TextField()),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "system_config",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=128, unique=True)),
                ("rank", models.IntegerField()),
                ("auto_bind", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("mode_type", models.SmallIntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="domain.department",
                    ),
                ),
            ],
            options={
                "db_table": "system_department",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("mode_type", models.SmallIntegerField(default=0)),
                ("avatar", models.CharField(blank=True, max_length=100, null=True)),
                ("nickname", models.CharField(default="", max_length=150)),
                ("gender", models.IntegerField(default=0)),
                ("phone", models.CharField(default="", max_length=16)),
                ("email", models.CharField(default="", max_length=254)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="domain_users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="domain_users",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="domain.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "system_user",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("status", models.BooleanField()),
                ("login_type", models.IntegerField()),
                ("ipaddress", models.CharField(blank=True, max_length=45, null=True)),
                ("browser", models.CharField(blank=True, max_length=255, null=True)),
                ("system", models.CharField(blank=True, max_length=255, null=True)),
                ("agent", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_login_log",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                ("module", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("business_type", models.CharField(max_length=128)),
                ("method", models.CharField(max_length=100)),
                ("request_method", models.CharField(max_length=10)),
                ("operator_type", models.CharField(max_length=50)),
                ("oper_name", models.CharField(max_length=50)),
                ("dept_name", models.CharField(max_length=50)),
                ("oper_url", models.CharField(max_length=255)),
                ("oper_ip", models.CharField(max_length=128)),
                ("oper_location", models.CharField(max_length=255)),
                ("oper_param", models.TextField()),
                ("json_result", models.TextField()),
                ("status", models.BooleanField()),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("cost_time", models.BigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_operation_log",
            },
        ),
        migrations.CreateModel(
            name="RoleMenu",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_menus",
                        to="domain.menu",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_menus",
                        to="domain.role",
                    ),
                ),
            ],
            options={
                "db_table": "system_role_menu",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.domain.models.base_model.generate_uuid_pk,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("modifier", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="domain.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_user_role",
            },
        ),
    ]
