# Generated by Django 5.2.7 on 2025-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationlog",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="operationlog",
            name="modifier",
        ),
        migrations.RemoveField(
            model_name="operationlog",
            name="updated_time",
        ),
        migrations.AddField(
            model_name="menumeta",
            name="dynamic_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="fixed_tag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="frame_loading",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="frame_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="is_hidden_tag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="is_keepalive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="is_show_menu",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="is_show_parent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="r_svg_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="transition_enter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="transition_leave",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menu",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menu",
            name="sort",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="menu",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="sort",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="rolemenu",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="rolemenu",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="updated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
