# Generated by Django 5.2.4 on 2025-10-15 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=128, unique=True, default=''),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=256, null=True, blank=True),
        ),
    ]