# Generated by Django 5.2.7 on 2025-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="mode_type",
            field=models.SmallIntegerField(default=0),
        ),
    ]
