# Generated by Django 5.2.4 on 2025-10-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_remove_operationlog_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlog",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]