# Generated by Django 5.2.7 on 2025-10-16 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_auto_20251015_2328"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.AddField(
            model_name="role",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="mode_type",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterModelTable(
            name="role",
            table="system_userrole",
        ),
        migrations.AlterModelTable(
            name="user",
            table="system_userinfo",
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=128, unique=True)),
                ("rank", models.IntegerField()),
                ("auto_bind", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("mode_type", models.SmallIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="domain.department",
                    ),
                ),
            ],
            options={
                "db_table": "system_deptinfo",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="domain.department",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="belong_users",
                to="domain.department",
            ),
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("status", models.BooleanField()),
                ("ipaddress", models.CharField(blank=True, max_length=39, null=True)),
                ("browser", models.CharField(blank=True, max_length=64, null=True)),
                ("system", models.CharField(blank=True, max_length=64, null=True)),
                ("agent", models.CharField(blank=True, max_length=128, null=True)),
                ("login_type", models.SmallIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_login_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_login_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_userloginlog",
            },
        ),
        migrations.CreateModel(
            name="MenuMeta",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("r_svg_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_show_menu", models.BooleanField()),
                ("is_show_parent", models.BooleanField()),
                ("is_keepalive", models.BooleanField()),
                ("frame_url", models.CharField(blank=True, max_length=255, null=True)),
                ("frame_loading", models.BooleanField()),
                (
                    "transition_enter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transition_leave",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_hidden_tag", models.BooleanField()),
                ("fixed_tag", models.BooleanField()),
                ("dynamic_level", models.IntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_menu_metas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_menu_metas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_menumeta",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("menu_type", models.SmallIntegerField()),
                ("name", models.CharField(max_length=128, unique=True)),
                ("rank", models.IntegerField()),
                ("path", models.CharField(max_length=255)),
                ("component", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField()),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="domain.menu",
                    ),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="domain.menumeta",
                    ),
                ),
            ],
            options={
                "db_table": "system_menu",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("module", models.CharField(blank=True, max_length=64, null=True)),
                ("path", models.CharField(blank=True, max_length=400, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=8, null=True)),
                ("ipaddress", models.CharField(blank=True, max_length=39, null=True)),
                ("browser", models.CharField(blank=True, max_length=64, null=True)),
                ("system", models.CharField(blank=True, max_length=64, null=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_result", models.TextField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_operation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_operationlog",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("value", models.TextField()),
                ("is_active", models.BooleanField()),
                ("access", models.BooleanField()),
                ("key", models.CharField(max_length=255, unique=True)),
                ("inherit", models.BooleanField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_config",
            },
        ),
        migrations.CreateModel(
            name="RoleMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="domain.menu"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="domain.role"
                    ),
                ),
            ],
            options={
                "db_table": "system_userrole_menu",
                "unique_together": {("role", "menu")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="domain.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_userinfo_roles",
                "unique_together": {("user", "role")},
            },
        ),
    ]
