# Generated by Django 5.2.7 on 2025-10-16 14:10

import app.domain.models.role
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_remove_role_permissions_role_creator_role_modifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.CharField(
                default=app.domain.models.role.generate_role_id,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
